LESSON_REG_ACTIVE = 1
LESSON_REG_INACTIVE = 2
LESSON_REG_PENDING_ENROLL = 3  # request from teacher
LESSON_REG_PENDING_DEROLL = 4
LESSON_REG_PENDING_JOIN = 5  # request from student
LESSON_REG_PENDING_QUIT = 6